# Версия схемы, которую мы используем.
# Зависит от установленной версии docker
# https://docs.docker.com/compose/compose-file/
version: "3"
# Определяем список сервисов — services
# Эти сервисы будут частью нашего приложения
services:

  app: # Имя сервиса
    build:
      # Контекст для сборки образа,
      # в данном случае, текущая директория
      context: .
      # Имя Docker-файла из которого будет собран образ
      dockerfile: Dockerfile
      # Команда, которая будет выполнена после старта сервиса
    env_file: .env
    command: /app/.venv/bin/python run.py
    networks:
      - bot
    depends_on:
      - redis

  redis:
    image: redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    networks:
      - bot

  scheduler:
    build:
      context: .
      dockerfile: app/workers/scheduler/Dockerfile
    env_file: .env
    command: /app/.venv/bin/python /app/.venv/bin/arq app.workers.scheduler.main.WorkerSettings
    networks:
      - bot
    depends_on:
      - redis
      - app

networks:
  bot:

volumes:
  redis-data: